### ISSUE TITLE
IssueImageUpload Error:  com.bugtags.library.obfuscated.am: javax.net.ssl.SSLHandshakeException:

### ISSUE THREAD

**Issue by jp1017** [bugtags/Bugtags-Android#8]
bugtags 1.3.3,  异常详情：

>IssueImageUpload Error: 
com.bugtags.library.obfuscated.am: javax.net.ssl.SSLHandshakeException: com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate: null
    at com.bugtags.library.obfuscated.at.e(BasicNetwork.java:96)
    at com.bugtags.library.obfuscated.an.run(NetworkDispatcher.java:99)
Caused by: javax.net.ssl.SSLHandshakeException: com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate: null
    at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:409)
    at com.android.okhttp.Connection.upgradeToTls(Connection.java:146)
    at com.android.okhttp.Connection.connect(Connection.java:107)
    at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:294)
    at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
    at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
    at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
    at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:89)
    at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:197)
    at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:254)
    at com.bugtags.library.obfuscated.av.b(HurlStack.java:215)
    at com.bugtags.library.obfuscated.av.a(HurlStack.java:202)
    at com.bugtags.library.obfuscated.av.a(HurlStack.java:101)
    at com.bugtags.library.obfuscated.at.e(BasicNetwork.java:56)
	... 1 more
Caused by: java.security.cert.CertificateException: com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate: null
    at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:308)
    at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:202)
    at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:611)
    at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
    at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:405)
	... 14 more
Caused by: com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate: null
    at com.android.org.bouncycastle.jce.provider.RFC3280CertPathUtilities.processCertA(RFC3280CertPathUtilities.java:1488)
    at com.android.org.bouncycastle.jce.provider.PKIXCertPathValidatorSpi.engineValidate(PKIXCertPathValidatorSpi.java:305)
    at java.security.cert.CertPathValidator.validate(CertPathValidator.java:190)
    at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:295)
	... 18 more
Caused by: java.security.cert.CertificateExpiredException
    at com.android.org.conscrypt.OpenSSLX509Certificate.checkValidity(OpenSSLX509Certificate.java:220)
    at com.android.org.bouncycastle.jce.provider.RFC3280CertPathUtilities.processCertA(RFC3280CertPathUtilities.java:1483)
	... 21 more

**Comment by kevinho** [comment]
这个问题，可能的原因是在https 握手的过程中，网络情况不好。
重试一下，看下

**Comment by jp1017** [comment]
好的 :smile:
