### ISSUE TITLE
有个莫名其妙的NullPointerException问题

### ISSUE THREAD

**Issue by donglua** [bugtags/Bugtags-Android#9]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String io.bugtags.agent.AgentConfiguration.getTrackingNetworkURLFilter()' on a null object reference
     at io.bugtags.agent.network.TransactionQueue.enqueue(TransactionQueue.java:69)
     at io.bugtags.agent.instrumentation.TransactionStateUtil.sendData(TransactionStateUtil.java:250)
     at io.bugtags.agent.instrumentation.okhttp3.OkHttp3TransactionStateUtil.addTransactionAndErrorData(OkHttp3TransactionStateUtil.java:149)
     at io.bugtags.agent.instrumentation.okhttp3.OkHttp3TransactionStateUtil.inspectAndInstrumentResponse(OkHttp3TransactionStateUtil.java:75)
     at io.bugtags.agent.instrumentation.okhttp3.CallExtension.checkResponse(CallExtension.java:72)
     at io.bugtags.agent.instrumentation.okhttp3.CallExtension.execute(CallExtension.java:49)
     at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
     at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:171)
     at rx.internal.operators.OperatorSubscribeOn$1$1$1.request(OperatorSubscribeOn.java:80)
     at rx.Subscriber.setProducer(Subscriber.java:211)
     at rx.internal.operators.OperatorSubscribeOn$1$1.setProducer(OperatorSubscribeOn.java:76)
     at rx.Subscriber.setProducer(Subscriber.java:205)
     at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
     at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
     at rx.Observable.unsafeSubscribe(Observable.java:10200)
     at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
     at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:228)
     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
     at java.lang.Thread.run(Thread.java:761)
```

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String io.bugtags.agent.AgentConfiguration.getTrackingNetworkURLFilter()' on a null object reference
    at io.bugtags.agent.network.TransactionQueue.enqueue(TransactionQueue.java:69)
    at io.bugtags.agent.instrumentation.TransactionStateUtil.sendData(TransactionStateUtil.java:250)
    at io.bugtags.agent.instrumentation.httpurl.HttpsURLConnectionExtension.addTransactionAndErrorData(HttpsURLConnectionExtension.java:502)
    at io.bugtags.agent.instrumentation.httpurl.HttpsURLConnectionExtension.disconnect(HttpsURLConnectionExtension.java:69)
    at cn.jpush.android.util.s.a(Unknown Source)
    at cn.jpush.android.util.aj.a(Unknown Source)
    at cn.jpush.android.api.d.run(Unknown Source)
```

**Comment by kevinho** [comment]
请更新 2.1.2，已修复这个问题。

**Comment by donglua** [comment]
ok
